### ISSUE TITLE
Ingester panic on shutdown

### ISSUE THREAD

**Issue by bboreham** [cortexproject/cortex#1085]
Running version `master-c824ad2f`
at the end of the log:

```
level=info ts=2018-10-18T15:24:52.854666978Z caller=transfer.go:247 msg="successfully sent chunks" to_ingester=10.244.253.152:9095
level=info ts=2018-10-18T15:24:52.87543753Z caller=lifecycler.go:343 msg="ingester removed from consul"
level=info ts=2018-10-18T15:24:52.875490858Z caller=lifecycler.go:267 msg="Ingester.loop() exited gracefully"
panic: close of closed channel
goroutine 1 [running]:
github.com/cortexproject/cortex/pkg/chunk/cache.(*backgroundCache).Stop(0xc4201f6420, 0x0, 0x0)
/go/src/github.com/cortexproject/cortex/pkg/chunk/cache/background.go:77 +0x2f
github.com/cortexproject/cortex/pkg/chunk.(*Fetcher).Stop(0xc42035e8c0)
/go/src/github.com/cortexproject/cortex/pkg/chunk/chunk_store_utils.go:92 +0x58
github.com/cortexproject/cortex/pkg/chunk.(*store).Stop(0xc4202de2a0)
/go/src/github.com/cortexproject/cortex/pkg/chunk/chunk_store.go:99 +0x32
github.com/cortexproject/cortex/pkg/chunk.compositeStore.Stop(0xc42036e0c0, 0x6, 0x8)
/go/src/github.com/cortexproject/cortex/pkg/chunk/composite_store.go:218 +0x42
main.main()
```

**Comment by tomwilkie** [comment]
I think this is due to the resuse of the same cache for multiple storages (used to be in `Opts`, now in `NewStore`).

I guess we can either (a) not share caches between store, (b) ignore multiple calls to cache or (c) not stop the caches in the store (as they don't "own" the cache lifecycle).  I think I prefer (b).  WDYT?
