### ISSUE TITLE
Alertmanager panics when no flags are specified

### ISSUE THREAD

**Issue by mateusz-gozdek-sociomantic** [cortexproject/cortex#1198]
Built from current master (518d8c603c0a5b306af6622e1e10d39c4525d8e0):
```
$ cmd/alertmanager/alertmanager -server.http-listen-port 8080
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x5a0eb0]

goroutine 56 [running]:
net/url.(*URL).String(0x0, 0x13c79e0, 0xd06100)
	/usr/local/go/src/net/url/url.go:742 +0x40
github.com/cortexproject/cortex/pkg/configs/client.(*AlertManagerConfigsAPI).GetConfigs(0xc420294a88, 0x0, 0x487496, 0x5c47468d, 0x1d83c5ec)
	/go/src/github.com/cortexproject/cortex/pkg/configs/client/configs.go:91 +0x62
github.com/cortexproject/cortex/pkg/alertmanager.(*MultitenantAlertmanager).poll.func1(0xd06100, 0xc42022bec0, 0x15, 0xbf09ef835d83c5ec)
	/go/src/github.com/cortexproject/cortex/pkg/alertmanager/multitenant.go:369 +0x42
github.com/cortexproject/cortex/vendor/github.com/weaveworks/common/instrument.CollectedRequest(0xd06080, 0xc4200b2010, 0xc84d4e, 0x15, 0xd04f40, 0xc42000e588, 0xcab100, 0xc420061cf0, 0x0, 0x0)
	/go/src/github.com/cortexproject/cortex/vendor/github.com/weaveworks/common/instrument/instrument.go:151 +0x1fa
github.com/cortexproject/cortex/pkg/alertmanager.(*MultitenantAlertmanager).poll(0xc420294a80, 0x0, 0x0, 0x0)
	/go/src/github.com/cortexproject/cortex/pkg/alertmanager/multitenant.go:367 +0xd2
github.com/cortexproject/cortex/pkg/alertmanager.(*MultitenantAlertmanager).loadAllConfigs(0xc420294a80, 0xcabc60)
	/go/src/github.com/cortexproject/cortex/pkg/alertmanager/multitenant.go:344 +0xe9
github.com/cortexproject/cortex/pkg/alertmanager.(*MultitenantAlertmanager).Run(0xc420294a80)
	/go/src/github.com/cortexproject/cortex/pkg/alertmanager/multitenant.go:299 +0x74
created by main.main
	/go/src/github.com/cortexproject/cortex/cmd/alertmanager/main.go:50 +0x212
```

I guess this is because of missing config flag.

**Comment by bboreham** [comment]
Sorry about that!  We are lacking in some basics, and most users of Cortex are not running `ruler` or `alertmanager` so don't trip over these things.

If you figure it out I would encourage a PR to add the info to https://github.com/cortexproject/cortex/blob/master/docs/arguments.md

FWIW this is (nearly) my set of args from production:

```
        args:
        - -server.http-listen-port=80
        - -alertmanager.configs.url=http://configs.cortex.svc.cluster.local.:80
        - -alertmanager.mesh.peer.service=mesh
        - -alertmanager.mesh.peer.host=alertmanager.cortex.svc.cluster.local
        - -alertmanager.mesh.peer.refresh-interval=1m
```

Thanks!

**Comment by gouthamve** [comment]
This is now fixed in the single binary version.
