### ISSUE TITLE
Panic when unable to retrieve credentials from AWS STS

### ISSUE THREAD

**Issue by awh** [cortexproject/cortex#1211]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x149d3de]

goroutine 770 [running]:
github.com/cortexproject/cortex/pkg/chunk/aws.dynamoDBRequestAdapter.Retryable(0xc42265a000, 0x1aa9ee2)
	/go/src/github.com/cortexproject/cortex/pkg/chunk/aws/dynamodb_storage_client.go:457 +0xe
github.com/cortexproject/cortex/pkg/chunk/aws.dynamoDBStorageClient.queryPage(0xc420478380, 0x4000000000000000, 0x0, 0x0, 0x0, 0x186a0, 0x3ff4cccccccccccd, 0x1b05684, 0x51, 0x1b0fe58, ...)
	/go/src/github.com/cortexproject/cortex/pkg/chunk/aws/dynamodb_storage_client.go:380 +0x38d
github.com/cortexproject/cortex/pkg/chunk/aws.dynamoDBStorageClient.query(0xc420478380, 0x4000000000000000, 0x0, 0x0, 0x0, 0x186a0, 0x3ff4cccccccccccd, 0x1b05684, 0x51, 0x1b0fe58, ...)
	/go/src/github.com/cortexproject/cortex/pkg/chunk/aws/dynamodb_storage_client.go:337 +0x472
github.com/cortexproject/cortex/pkg/chunk/aws.(dynamoDBStorageClient).(github.com/cortexproject/cortex/pkg/chunk/aws.query)-fm(0x1c655e0, 0xc4225eb050, 0xc420896300, 0x16, 0xc422532100, 0x3b, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cortexproject/cortex/pkg/chunk/aws/dynamodb_storage_client.go:285 +0xb4
github.com/cortexproject/cortex/pkg/chunk/util.DoParallelQueries.func1(0x1c655e0, 0xc4224e5890, 0xc4224a36e0, 0xc4224a3740, 0xc422656200, 0xc422648860)
	/go/src/github.com/cortexproject/cortex/pkg/chunk/util/util.go:42 +0x121
created by github.com/cortexproject/cortex/pkg/chunk/util.DoParallelQueries
	/go/src/github.com/cortexproject/cortex/pkg/chunk/util/util.go:34 +0xf9
```

**Comment by bboreham** [comment]
That goroutine is spawned indirectly; it isn't obvious how the crash arises.
Can you share more details about the config?

**Comment by awh** [comment]
* Trace is from the querier, which is deployed without specifying access tokens in the s3 and dynamodb URLs
* It is deployed alongside https://github.com/uswitch/kiam, which is intercepting calls from the AWS client library in the querier to the EC2 metadata service
* The querier deployment has an annotation which specifies an appropriate IAM role
* The kiam server was misconfigured, such that it was unable to contact STS. Consequently, the kiam agent emitted the following error when the AWS client in the querier contacted it for credentials:
    ```
    {"addr":"10.244.243.158:45092","level":"error","method":"GET","msg":"error processing request: error fetching credentials: rpc error: code = DeadlineExceeded desc = context deadline exceeded","path":"/latest/meta-data/iam/security-credential /dev_chunk_reader_role","status":500,"time":"2019-01-31T10:47:45Z"}
    ```
* The panic is provoked upon trying to execute a query
