### ISSUE TITLE
Ingester hangs when using -limits.per-user-override-config

### ISSUE THREAD

**Issue by bboreham** [cortexproject/cortex#1596]
After #1549 was merged, ingester hangs on startup when flag `-limits.per-user-override-config` is specified.

Stack trace:
```
goroutine 1 [select]:
github.com/cortexproject/cortex/pkg/util/validation.(*OverridesManager).loop(0xc000598000)
	/go/src/github.com/cortexproject/cortex/pkg/util/validation/override.go:63 +0xf9
github.com/cortexproject/cortex/pkg/util/validation.NewOverridesManager(0x2540be400, 0x7ffc2fd8d209, 0x7, 0x2bce180, 0x2688ae0, 0xc00041c5b0, 0xc00034d940, 0xc000341801, 0x1000000007d7a3c)
	/go/src/github.com/cortexproject/cortex/pkg/util/validation/override.go:50 +0xe3
github.com/cortexproject/cortex/pkg/util/validation.NewOverrides(0x40d86a0000000000, 0xc350, 0x0, 0x2adcf02, 0x7, 0x2ae468b, 0xb, 0x400, 0x800, 0x19, ...)
	/go/src/github.com/cortexproject/cortex/pkg/util/validation/limits.go:113 +0xfa
github.com/cortexproject/cortex/pkg/cortex.(*Cortex).initOverrides(0xc00064d180, 0xc000148600, 0x1, 0xc0004058c8)
	/go/src/github.com/cortexproject/cortex/pkg/cortex/modules.go:164 +0x9c
github.com/cortexproject/cortex/pkg/cortex.(*Cortex).initModule(0xc00064d180, 0xc000148600, 0x1, 0x3, 0xc000341aa0)
	/go/src/github.com/cortexproject/cortex/pkg/cortex/cortex.go:200 +0x23a
github.com/cortexproject/cortex/pkg/cortex.(*Cortex).init(0xc00064d180, 0xc000148600, 0x4, 0x0, 0xc000341c30)
	/go/src/github.com/cortexproject/cortex/pkg/cortex/cortex.go:189 +0x85
github.com/cortexproject/cortex/pkg/cortex.New(0x4, 0x1, 0x2adfc04, 0x9, 0x2adb0d5, 0x6, 0x50, 0x2387, 0x101, 0x6fc23ac00, ...)
	/go/src/github.com/cortexproject/cortex/pkg/cortex/cortex.go:147 +0xd5
main.main()
	/go/src/github.com/cortexproject/cortex/cmd/cortex/main.go:60 +0x46e
```

**Comment by csmarchbanks** [comment]
Fixed by #1595
