### ISSUE TITLE
Updated vendor alertmanager panics

### ISSUE THREAD

**Issue by jtlisi** [cortexproject/cortex#1659]
Currently the alertmanager panics when run. 
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xc2b640]

goroutine 435 [running]:
github.com/cortexproject/cortex/vendor/github.com/prometheus/alertmanager/types.(*memMarker).registerMetrics(0xc000c6f140, 0x0, 0x0)
	/go/src/github.com/cortexproject/cortex/vendor/github.com/prometheus/alertmanager/types/types.go:125 +0x120
github.com/cortexproject/cortex/vendor/github.com/prometheus/alertmanager/types.NewMarker(...)
	/go/src/github.com/cortexproject/cortex/vendor/github.com/prometheus/alertmanager/types/types.go:97
github.com/cortexproject/cortex/pkg/alertmanager.New(0xc000c135e0, 0xc000c135e0, 0x34e0ce0, 0xc000896840)
	/go/src/github.com/cortexproject/cortex/pkg/alertmanager/alertmanager.go:101 +0x6d0
github.com/cortexproject/cortex/pkg/alertmanager.(*MultitenantAlertmanager).newAlertmanager(0xc000982120, 0xc000c79038, 0x4, 0xc0004ca230, 0x0, 0x0, 0xc0009856e0)
	/go/src/github.com/cortexproject/cortex/pkg/alertmanager/multitenant.go:445 +0xfe
github.com/cortexproject/cortex/pkg/alertmanager.(*MultitenantAlertmanager).setConfig(0xc000982120, 0xc000a16740, 0x4, 0x4)
	/go/src/github.com/cortexproject/cortex/pkg/alertmanager/multitenant.go:406 +0xcca
github.com/cortexproject/cortex/pkg/alertmanager.(*MultitenantAlertmanager).addNewConfigs(0xc000982120, 0xc00020a308, 0x1, 0x1)
	/go/src/github.com/cortexproject/cortex/pkg/alertmanager/multitenant.go:305 +0x1fa
github.com/cortexproject/cortex/pkg/alertmanager.(*MultitenantAlertmanager).Run(0xc000982120)
	/go/src/github.com/cortexproject/cortex/pkg/alertmanager/multitenant.go:233 +0x82
created by github.com/cortexproject/cortex/pkg/cortex.(*Cortex).initAlertmanager
	/go/src/github.com/cortexproject/cortex/pkg/cortex/modules.go:383 +0xea
```

This is caused by the following call:
```go
	am.marker = types.NewMarker(nil)
```

New marker can not take a nil registry or else it will panic.

**Comment by bboreham** [comment]
Would be good to get an integration test for the alertmanager, even if only a trivial one.
We already have some code setting up a Postgres database in the Go tests.
