### ISSUE TITLE
Lazy querier can have tens of thousands of stuck goroutines 

### ISSUE THREAD

**Issue by bboreham** [cortexproject/cortex#1832]
I suspect when something goes wrong the querier stops reading responses so all the remaining ones are abandoned on an error send.

Profile shows them stuck here:

https://github.com/cortexproject/cortex/blob/6f74b9c4bcffcce6e4149a354fc4cbf2dc390a2f/pkg/querier/lazy_querier.go#L28

![image](https://user-images.githubusercontent.com/8125524/68994698-e3ba8a80-083a-11ea-9c53-63dd334f871b.png)

**Comment by bboreham** [comment]
Happened again when Consul blipped.  Same stack trace:

```
goroutine 33232678 [chan send, 265 minutes]:
github.com/cortexproject/cortex/pkg/querier.lazyQuerier.Select.func1(0x3675e60, 0xc005809bd0, 0xc00ceebce0, 0xc007f77150, 0x2, 0x2, 0xc0141de1e0)
	/go/src/github.com/cortexproject/cortex/pkg/querier/lazy_querier.go:28 +0x103
created by github.com/cortexproject/cortex/pkg/querier.lazyQuerier.Select
	/go/src/github.com/cortexproject/cortex/pkg/querier/lazy_querier.go:25 +0xa3
```
