### ISSUE TITLE
runtime error: integer divide by zero

### ISSUE THREAD

**Issue by pstibrany** [cortexproject/cortex#2603]
Found in logs while investigating customer query error:

```
level=error ts=2020-05-19T07:16:14.487217809Z caller=engine.go:810 msg="runtime panic in parser" err="runtime error: integer divide by zero" stacktrace="goroutine 1700 [running]:
github.com/prometheus/prometheus/promql.(*evaluator).recover(0xc001e26800, 0xc001e26590)
	/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20200213233353-b90be6f32a33/promql/engine.go:808 +0xd8
panic(0x2e7e120, 0x5612dd0)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/prometheus/prometheus/promql.(*evaluator).eval(0xc001e26800, 0x3b66900, 0xc001cd9e90, 0x0, 0xc001e250f8)
	/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20200213233353-b90be6f32a33/promql/engine.go:1330 +0x35d3
github.com/prometheus/prometheus/promql.(*evaluator).evalSubquery(0xc001e26800, 0xc001cd9e90, 0x345b36b)
	/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20200213233353-b90be6f32a33/promql/engine.go:1005 +0x59
github.com/prometheus/prometheus/promql.(*evaluator).eval(0xc001e26800, 0x3b667c0, 0xc001cd9ec0, 0xc001e761b0, 0x0)
	/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20200213233353-b90be6f32a33/promql/engine.go:1074 +0x222c
github.com/prometheus/prometheus/promql.(*evaluator).rangeEval(0xc001e26800, 0xc001e26158, 0xc001e26220, 0x2, 0x2, 0x0, 0x564a1a0, 0x0)
	/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20200213233353-b90be6f32a33/promql/engine.go:892 +0x1408
github.com/prometheus/prometheus/promql.(*evaluator).eval(0xc001e26800, 0x3b66780, 0xc001e0a500, 0x3b65b80, 0xc001e76120)
	/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20200213233353-b90be6f32a33/promql/engine.go:1258 +0x33ea
github.com/prometheus/prometheus/promql.(*evaluator).Eval(0xc001e26800, 0x3b66780, 0xc001e0a500, 0x0, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20200213233353-b90be6f32a33/promql/engine.go:819 +0x99
github.com/prometheus/prometheus/promql.(*Engine).execEvalStmt(0xc0000af740, 0x3b65b80, 0xc001e76030, 0xc0016f9d40, 0xc001df6f00, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20200213233353-b90be6f32a33/promql/engine.go:588 +0xdba
github.com/prometheus/prometheus/promql.(*Engine).exec(0xc0000af740, 0x3b65b80, 0xc001e76030, 0xc0016f9d40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20200213233353-b90be6f32a33/promql/engine.go:492 +0x4c6
github.com/prometheus/prometheus/promql.(*query).Exec(0xc0016f9d40, 0x3b65b80, 0xc001cd9110, 0xc001e55500)
	/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20200213233353-b90be6f32a33/promql/engine.go:192 +0x94
github.com/cortexproject/cortex/pkg/querier/queryrange.(*queryShard).Do(0xc0006f0d20, 0x3b65b80, 0xc001cd9110, 0x3bae7c0, 0xc001e0a4c0, 0x0, 0xc001cd9ce0, 0x0, 0xc000543080)
	/go/src/github.com/cortexproject/cortex/pkg/querier/queryrange/querysharding.go:227 +0x3ae
github.com/cortexproject/cortex/pkg/querier/queryrange.(*astMapperware).Do(0xc000105180, 0x3b65b80, 0xc001cd9110, 0x3bae7c0, 0xc0019b5800, 0xc0019d0fc0, 0x4c6ee6, 0x5ec387be, 0x1cfb0b5e)
	/go/src/github.com/cortexproject/cortex/pkg/querier/queryrange/querysharding.go:195 +0x7bc
github.com/cortexproject/cortex/pkg/querier/queryrange.InstrumentMiddleware.func1.1.1(0x3b65b80, 0xc001cd9110, 0xc, 0xbfa8ffcf9cfb0b5e)
	/go/src/github.com/cortexproject/cortex/pkg/querier/queryrange/instrumentation.go:28 +0x62
github.com/weaveworks/common/instrument.CollectedRequest(0x3b65b80, 0xc001cd8e40, 0x344153e, 0xc, 0x3b43900, 0xc0001e21c8, 0x361ffe8, 0xc0019d1178, 0xc001b8b550, 0x1)
	/go/pkg/mod/github.com/weaveworks/common@v0.0.0-20200429090833-ac38719f57dd/instrument/instrument.go:152 +0x268
github.com/cortexproject/cortex/pkg/querier/queryrange.InstrumentMiddleware.func1.1(0x3b65b80, 0xc001cd8e40, 0x3bae7c0, 0xc0019b5800, 0xc0019d1158, 0xc0019d1268, 0x2097408, 0xc0000aef00)
	/go/src/github.com/cortexproject/cortex/pkg/querier/queryrange/instrumentation.go:26 +0xe9
github.com/cortexproject/cortex/pkg/querier/queryrange.HandlerFunc.Do(0xc0002525c0, 0x3b65b80, 0xc001cd8e40, 0x3bae7c0, 0xc0019b5800, 0xc0019d1268, 0x208aaed, 0xc001cd8e40, 0x2c665c0)
	/go/src/github.com/cortexproject/cortex/pkg/querier/queryrange/roundtrip.go:96 +0x4e
github.com/cortexproject/cortex/pkg/querier/queryrange.(*shardSplitter).parallel(0xc0002526c0, 0x3b65b80, 0xc001cd8e40, 0x3bae7c0, 0xc0019b5800, 0x0, 0x0, 0x0, 0x0, 0x3b65b80, ...)
	/go/src/github.com/cortexproject/cortex/pkg/querier/queryrange/querysharding.go:267 +0x638
github.com/cortexproject/cortex/pkg/querier/queryrange.(*shardSplitter).Do(0xc0002526c0, 0x3b65b80, 0xc001cd8e40, 0x3bae7c0, 0xc0019b5800, 0x0, 0x0, 0xc001b8b550, 0x1)
	/go/src/github.com/cortexproject/cortex/pkg/querier/queryrange/querysharding.go:257 +0xcb
github.com/cortexproject/cortex/pkg/querier/queryrange.resultsCache.handleMiss(0x3ae6fe0, 0xc0008a19e0, 0x0, 0x0, 0xa, 0x2710, 0x0, 0x400, 0x64, 0x7ffcac471c98, ...)
	/go/src/github.com/cortexproject/cortex/pkg/querier/queryrange/results_cache.go:244 +0x80
github.com/cortexproject/cortex/pkg/querier/queryrange.resultsCache.Do(0x3ae6fe0, 0xc0008a19e0, 0x0, 0x0, 0xa, 0x2710, 0x0, 0x400, 0x64, 0x7ffcac471c98, ...)
	/go/src/github.com/cortexproject/cortex/pkg/querier/queryrange/results_cache.go:183 +0x526
github.com/cortexproject/cortex/pkg/querier/queryrange.InstrumentMiddleware.func1.1.1(0x3b65b80, 0xc001cd8e10, 0xd, 0xbfa8ffcf9cf669bd)
	/go/src/github.com/cortexproject/cortex/pkg/querier/queryrange/instrumentation.go:28 +0x62
github.com/weaveworks/common/instrument.CollectedRequest(0x3b65ac0, 0xc0019b59c0, 0x3443cfe, 0xd, 0x3b43900, 0xc0001e2178, 0x361ffe8, 0xc0019c7e78, 0x170e, 0x3)
	/go/pkg/mod/github.com/weaveworks/common@v0.0.0-20200429090833-ac38719f57dd/instrument/instrument.go:152 +0x268
github.com/cortexproject/cortex/pkg/querier/queryrange.InstrumentMiddleware.func1.1(0x3b65ac0, 0xc0019b59c0, 0x3bae7c0, 0xc0019b5800, 0xc001656ba0, 0xc001985f60, 0x1, 0x101)
	/go/src/github.com/cortexproject/cortex/pkg/querier/queryrange/instrumentation.go:26 +0xe9
github.com/cortexproject/cortex/pkg/querier/queryrange.HandlerFunc.Do(0xc0002527c0, 0x3b65ac0, 0xc0019b59c0, 0x3bae7c0, 0xc0019b5800, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cortexproject/cortex/pkg/querier/queryrange/roundtrip.go:96 +0x4e
github.com/cortexproject/cortex/pkg/querier/queryrange.DoRequests.func2(0xc001656ba0, 0x3aecb00, 0xc0002527c0, 0xc001b8b0d0, 0xc001656c60, 0xc001656c00)
	/go/src/github.com/cortexproject/cortex/pkg/querier/queryrange/limits.go:85 +0xbb
created by github.com/cortexproject/cortex/pkg/querier/queryrange.DoRequests
	/go/src/github.com/cortexproject/cortex/pkg/querier/queryrange/limits.go:83 +0x2ec
```

**Comment by pstibrany** [comment]
Turning off query-sharding avoids the bug.

**Comment by owen-d** [comment]
This is because we don't call `promql.SetDefaultEvaluationInterval(cfg.Querier.DefaultEvaluationInterval)`, which mutates a package level variable in the promql package and is eventually used in division.

We currently do this in the querier:
https://github.com/cortexproject/cortex/blob/master/pkg/querier/querier.go#L134
