### ISSUE TITLE
Alertmanager segfaults if I don't pass the -alertmanager.web.external-url flag

### ISSUE THREAD

**Issue by samitpal** [cortexproject/cortex#2704]
Not sure if it is an issue. But when I look at the documentation for alertmanager, it doesn't seem to me that `-alertmanager.web.external-url` flag is a required flag. Here is what happens when I don't pass that flag. It works fine with that flag though.

```

$ sudo docker run --rm  --name=alertmanager  --network=host  cortex:v1.0.1 alertmanager.configs.url=http://configs.cortex:3001  -server.http-listen-port 2001 -server.grpc-listen-port 2002 -log.level=debug  -target alertmanager
level=info ts=2020-06-09T15:57:57.010945071Z caller=server.go:147 http=[::]:2001 grpc=[::]:2002 msg="server listening on addresses"
level=debug ts=2020-06-09T15:57:57.012990789Z caller=cluster.go:149 component=cluster msg="resolved peers to following addresses" peers=
level=info ts=2020-06-09T15:57:57.024781121Z caller=cluster.go:161 component=cluster msg="setting advertise address explicitly" addr=10.0.2.15 port=9094
level=debug ts=2020-06-09T15:57:57.0262938Z caller=delegate.go:230 component=cluster received=NotifyJoin node=01EACWTVX1BCH35X2KV4CT1R4D addr=10.0.2.15:9094
level=debug ts=2020-06-09T15:57:57.026771062Z caller=cluster.go:233 component=cluster msg="joined cluster" peers=0
level=info ts=2020-06-09T15:57:57.027893802Z caller=main.go:109 msg="Starting Cortex" version="(version=, branch=, revision=)"
level=info ts=2020-06-09T15:57:57.029518485Z caller=cluster.go:623 component=cluster msg="Waiting for gossip to settle..." interval=200ms
level=debug ts=2020-06-09T15:57:57.029920472Z caller=module_service.go:48 msg="module waiting for initialization" module=alertmanager waiting_for=server
level=info ts=2020-06-09T15:57:57.030184558Z caller=module_service.go:58 msg=initialising module=alertmanager
level=debug ts=2020-06-09T15:57:57.046158906Z caller=multitenant.go:283 component=MultiTenantAlertmanager msg="initial configuration load" num_configs=2
level=debug ts=2020-06-09T15:57:57.046604378Z caller=multitenant.go:312 component=MultiTenantAlertmanager msg="adding configurations" num_configs=2
level=debug ts=2020-06-09T15:57:57.046985744Z caller=multitenant.go:400 component=MultiTenantAlertmanager msg="setting config" user=team-X
level=debug ts=2020-06-09T15:57:57.047624125Z caller=multitenant.go:429 component=MultiTenantAlertmanager msg="initializing new per-tenant alertmanager" user=team-X
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x14da0a0]

goroutine 337 [running]:
github.com/cortexproject/cortex/pkg/alertmanager.New(0xc00017c6e0, 0xc00017c690, 0xc00064f0e0, 0xc00068e300, 0xc)
	/go/src/github.com/cortexproject/cortex/pkg/alertmanager/alertmanager.go:171 +0xe90
github.com/cortexproject/cortex/pkg/alertmanager.(*MultitenantAlertmanager).newAlertmanager(0xc0007ea600, 0xc000654d6a, 0x6, 0xc0006ca770, 0x0, 0x0, 0xc00036c960)
	/go/src/github.com/cortexproject/cortex/pkg/alertmanager/multitenant.go:451 +0x183
github.com/cortexproject/cortex/pkg/alertmanager.(*MultitenantAlertmanager).setConfig(0xc0007ea600, 0xc000654d6a, 0x6, 0xc000122750, 0x8b, 0x0, 0x0, 0x0, 0x2f119a0, 0x3a49680)
	/go/src/github.com/cortexproject/cortex/pkg/alertmanager/multitenant.go:430 +0xac9
github.com/cortexproject/cortex/pkg/alertmanager.(*MultitenantAlertmanager).syncConfigs(0xc0007ea600, 0xc000835140)
	/go/src/github.com/cortexproject/cortex/pkg/alertmanager/multitenant.go:314 +0x2e0
github.com/cortexproject/cortex/pkg/alertmanager.(*MultitenantAlertmanager).starting(0xc0007ea600, 0x3a96880, 0xc00078a780, 0x1, 0xc000836530)
	/go/src/github.com/cortexproject/cortex/pkg/alertmanager/multitenant.go:247 +0x39
github.com/cortexproject/cortex/pkg/util/services.(*BasicService).main(0xc00004c630)
	/go/src/github.com/cortexproject/cortex/pkg/util/services/basic_service.go:134 +0x459
created by github.com/cortexproject/cortex/pkg/util/services.(*BasicService).StartAsync.func1
	/go/src/github.com/cortexproject/cortex/pkg/util/services/basic_service.go:96 +0xa8_
```

**Comment by pracucci** [comment]
Thanks @samitpal for reporting it! This is definitely a bug we should fix. @jtlisi would you mind taking a look, please?

**Comment by pracucci** [comment]
_This is still valid._

**Comment by gotjosh** [comment]
I'd argue that this should be a required field. Without it, you can't access the Alertmanager UI nor its Prometheus-based API (the configuration API or cortex-specific endpoints would be though).

The extra angle here is that there might a be a case where you'd like to test/set Alertmanager configuration for tenants but not give them access to the UI/APIs just yet... but that seems unlikely?

**Comment by pracucci** [comment]
I believe the main point of the issue is that, even if this is a required field, it should error out (giving details) but not panic. From the panic you can't even understand what's wrong in the config.

**Comment by pracucci** [comment]
> I'd argue that this should be a required field

It's already a required field, but not checked. We should validate it before running the alertmanager.
