### ISSUE TITLE
Query Frontend occasionally panics: "concurrent map iteration and map write"

### ISSUE THREAD

**Issue by joe-elliott** [cortexproject/cortex#2763]
Query-frontend occasionally panics with the following message:

`fatal error: concurrent map iteration and map write`

This appears to be beneath query sharding:

```
goroutine 57546 [running]:
runtime.throw(0x3797fdd, 0x26)
        /usr/local/go/src/runtime/panic.go:774 +0x72 fp=0xc001d82a20 sp=0xc001d829f0 pc=0x42f892
runtime.mapiternext(0xc001d82b58)
        /usr/local/go/src/runtime/map.go:858 +0x579 fp=0xc001d82aa8 sp=0xc001d82a20 pc=0x40f589
runtime.mapiterinit(0x30754a0, 0xc002713b00, 0xc001d82b58)
        /usr/local/go/src/runtime/map.go:848 +0x1c3 fp=0xc001d82ac8 sp=0xc001d82aa8 pc=0x40ef23
github.com/cortexproject/cortex/pkg/querier/queryrange.headersMapToPrometheusResponseHeaders(0xc002713b00, 0x372ea06, 0x6, 0x0)
        /go/src/github.com/cortexproject/cortex/pkg/querier/queryrange/querysharding.go:327 +0x7b fp=0xc001d82bc8 sp=0xc001d82ac8 pc=0x2ae82eb
github.com/cortexproject/cortex/pkg/querier/queryrange.(*queryShard).Do(0xc000a46180, 0x3ee0260, 0xc002713680, 0x3f35b40, 0xc0023f7a00, 0x0, 0xc002713860, 0x0, 0xc0005e6660)
        /go/src/github.com/cortexproject/cortex/pkg/querier/queryrange/querysharding.go:239 +0x449 fp=0xc001d82d30 sp=0xc001d82bc8 pc=0x2ae74c9
github.com/cortexproject/cortex/pkg/querier/queryrange.(*astMapperware).Do(0xc0003c3ce0, 0x3ee0260, 0xc002713680, 0x3f35b40, 0xc0018eff00, 0xc001d82fb8, 0x4c6f76, 0x5ef0bdd9, 0x61b48ac)
        /go/src/github.com/cortexproject/cortex/pkg/querier/queryrange/querysharding.go:195 +0x7bc fp=0xc001d82f68 sp=0xc001d82d30 pc=0x2ae6f2c
github.com/cortexproject/cortex/pkg/querier/queryrange.InstrumentMiddleware.func1.1.1(0x3ee0260, 0xc002713680, 0xc, 0xbfb44d56461b48ac)
        /go/src/github.com/cortexproject/cortex/pkg/querier/queryrange/instrumentation.go:28 +0x62 fp=0xc001d82fc8 sp=0xc001d82f68 pc=0x2af1dc2
github.com/weaveworks/common/instrument.CollectedRequest(0x3ee0260, 0xc0023d5590, 0x373c9a1, 0xc, 0x3ebb360, 0xc000b2a308, 0x392c728, 0xc001d83170, 0xc000d58230, 0x1)
        /go/src/github.com/cortexproject/cortex/vendor/github.com/weaveworks/common/instrument/instrument.go:152 +0x268 fp=0xc001d83110 sp=0xc001d82fc8 pc=0xba1d28
```

**Comment by joe-elliott** [comment]
Full dump attached

[out.txt](https://github.com/cortexproject/cortex/files/4813962/out.txt)
