### ISSUE TITLE
Panic in indexShard

### ISSUE THREAD

**Issue by pstibrany** [cortexproject/cortex#3541]
Observed panic in Cortex chunks code (when used from Loki).

```
panic: runtime error: slice bounds out of range [3:2]
goroutine 114 [running]:
github.com/cortexproject/cortex/pkg/ingester/index.(*indexShard).delete(0xc004bee870, 0xc005c82340, 0xd, 0xd, 0xdd5778b83ef6a735)
	/src/loki/vendor/github.com/cortexproject/cortex/pkg/ingester/index/index.go:247 +0x4f6
github.com/cortexproject/cortex/pkg/ingester/index.(*InvertedIndex).Delete(0xc00090f540, 0xc005c82340, 0xd, 0xd, 0xdd5778b83ef6a735)
	/src/loki/vendor/github.com/cortexproject/cortex/pkg/ingester/index/index.go:85 +0x85
github.com/grafana/loki/pkg/ingester.(*Ingester).removeFlushedChunks(0xc000701400, 0xc000477040, 0xc01d7fc3c0)
	/src/loki/pkg/ingester/flush.go:305 +0x245
github.com/grafana/loki/pkg/ingester.(*Ingester).sweepInstance(0xc000701400, 0xc000477040, 0x0)
	/src/loki/pkg/ingester/flush.go:159 +0x138
github.com/grafana/loki/pkg/ingester.(*Ingester).sweepUsers(0xc000701400, 0xc00bc9ff00)
	/src/loki/pkg/ingester/flush.go:149 +0x6c
github.com/grafana/loki/pkg/ingester.(*Ingester).loop(0xc000701400)
	/src/loki/pkg/ingester/ingester.go:247 +0xc5
created by github.com/grafana/loki/pkg/ingester.(*Ingester).starting
	/src/loki/pkg/ingester/ingester.go:196 +0x1cf
```

**Comment by pracucci** [comment]
Fixed by #3543.
