### ISSUE TITLE
Cortex panic: runtime error: slice bounds out of range on query

### ISSUE THREAD

**Issue by nivekuil** [cortexproject/cortex#3942]
**Describe the bug**
Ran a query in grafana for a 20 minute block 30 hours ago. Cortex crashed.

**To Reproduce**
Don't know, has only happened once.

**Expected behavior**
The query to succeed, or a helpful error

**Environment:**
Docker
master-15c4426 (1.7.0+)

**Storage Engine**
- [X] Blocks
- [ ] Chunks

**Additional Context**
```
level=warn ts=2021-03-11T18:56:46.903431025Z caller=bucket.go:2013 org_id=fake block=01F0FKNHH7AWS1N1VV943WK01W msg="series size exceeded expected size; refetching" id=1921344 serieslength=115 maxSeriesSize=65536
level=warn ts=2021-03-11T18:56:46.904033204Z caller=bucket.go:2013 org_id=fake block=01F0G1D0177AXE6F2DZ8SQGJ2M msg="series size exceeded expected size; refetching" id=1920416 serieslength=115 maxSeriesSize=65536
level=warn ts=2021-03-11T18:56:46.904607331Z caller=bucket.go:2013 org_id=fake block=01F0H3QM97H9TWKW4MW7GQZT4X msg="series size exceeded expected size; refetching" id=1924016 serieslength=115 maxSeriesSize=65536
level=warn ts=2021-03-11T18:56:46.905157864Z caller=grpc_logging.go:55 method=/gatewaypb.StoreGateway/Series duration=1m5.969822782s err="rpc error: code = Aborted desc = fetch series for block 01F0FKNHH7AWS1N1VV943WK01W: expanded matching posting: get postings: invalid size" msg="gRPC\n"
level=warn ts=2021-03-11T18:56:46.905750505Z caller=grpc_logging.go:55 method=/gatewaypb.StoreGateway/Series duration=1m6.030023696s err="rpc error: code = Aborted desc = fetch series for block 01F0FKNHH7AWS1N1VV943WK01W: expanded matching posting: get postings: invalid size" msg="gRPC\n"
level=error ts=2021-03-11T18:56:46.906502286Z caller=retry.go:73 org_id=fake traceID=46feacee77d0705c msg="error processing request" try=0 err="rpc error: code = Code(500) desc = {\"status\":\"error\",\"errorType\":\"internal\",\"error\":\"expanding series: failed to receive series from 10.0.26.97:9095: rpc error: code = Aborted desc = fetch series for block 01F0FKNHH7AWS1N1VV943WK01W: expanded matching posting: get postings: invalid size\"}"
level=warn ts=2021-03-11T18:56:46.906743108Z caller=grpc_logging.go:55 method=/gatewaypb.StoreGateway/Series duration=1m6.02971621s err="rpc error: code = Aborted desc = fetch series for block 01F0GF4EH7DJ0W6TGCAWM61D55: populate chunk: unsupported chunk encoding 0" msg="gRPC\n"
level=warn ts=2021-03-11T18:56:46.907800471Z caller=grpc_logging.go:55 method=/gatewaypb.StoreGateway/Series duration=1m5.978238238s err="rpc error: code = Aborted desc = fetch series for block 01F0G1D0177AXE6F2DZ8SQGJ2M: expanded matching posting: get postings: invalid size" msg="gRPC\n"
level=warn ts=2021-03-11T18:56:46.908269562Z caller=grpc_logging.go:55 duration=1m5.979781995s method=/gatewaypb.StoreGateway/Series err="rpc error: code = Aborted desc = fetch series for block 01F0G1D0177AXE6F2DZ8SQGJ2M: expanded matching posting: get postings: invalid size" msg="gRPC\n"
level=error ts=2021-03-11T18:56:46.909265189Z caller=retry.go:73 org_id=fake traceID=5bbdb5d204eb6960 msg="error processing request" try=0 err="rpc error: code = Code(500) desc = {\"status\":\"error\",\"errorType\":\"internal\",\"error\":\"expanding series: failed to receive series from 10.0.26.97:9095: rpc error: code = Aborted desc = fetch series for block 01F0GF4EH7DJ0W6TGCAWM61D55: populate chunk: unsupported chunk encoding 0\"}"
vel=warn ts=2021-03-11T18:56:47.165332631Z caller=grpc_logging.go:55 method=/gatewaypb.StoreGateway/Series duration=1m6.235011645s err="rpc error: code = Aborted desc = fetch series for block 01F0FV9BE7HKM51VNBDDB0NA2C: populate chunk: unsupported chunk encoding 101" msg="gRPC\n"
level=error ts=2021-03-11T18:56:47.166326585Z caller=retry.go:73 org_id=fake traceID=46feacee77d0705c msg="error processing request" try=0 err="rpc error: code = Code(500) desc = {\"status\":\"error\",\"errorType\":\"internal\",\"error\":\"expanding series: failed to receive series from 10.0.26.97:9095: rpc error: code = Aborted desc = fetch series for block 01F0FV9BE7HKM51VNBDDB0NA2C: populate chunk: unsupported chunk encoding 101\"}"
level=warn ts=2021-03-11T18:56:47.166433325Z caller=grpc_logging.go:55 method=/gatewaypb.StoreGateway/Series duration=1m6.237273828s err="rpc error: code = Aborted desc = fetch series for block 01F0FV9BE7HKM51VNBDDB0NA2C: expanded matching posting: get postings: read postings range: get range reader: context canceled" msg="gRPC\n"
level=warn ts=2021-03-11T18:56:47.166491023Z caller=grpc_logging.go:55 duration=1m6.231671859s method=/gatewaypb.StoreGateway/Series err="rpc error: code = Aborted desc = fetch series for block 01F0FV9BE7HKM51VNBDDB0NA2C: expanded matching posting: get postings: read postings range: get range reader: context canceled" msg="gRPC\n"
level=warn ts=2021-03-11T18:56:47.201282391Z caller=bucket.go:2013 org_id=fake block=01F0FV9BE7HKM51VNBDDB0NA2C msg="series size exceeded expected size; refetching" id=11086400 serieslength=115 maxSeriesSize=65536
level=warn ts=2021-03-11T18:56:47.201876456Z caller=grpc_logging.go:55 method=/gatewaypb.StoreGateway/Series duration=1m6.325530144s err="rpc error: code = Aborted desc = fetch series for block 01F0FV9BE7HKM51VNBDDB0NA2C: expanded matching posting: get postings: invalid size" msg="gRPC\n"
level=warn ts=2021-03-11T18:56:47.20348336Z caller=bucket.go:2013 org_id=fake block=01F0FV9BE7HKM51VNBDDB0NA2C msg="series size exceeded expected size; refetching" id=11086400 serieslength=115 maxSeriesSize=65536
level=warn ts=2021-03-11T18:56:47.20442683Z caller=grpc_logging.go:55 duration=1m6.327720212s method=/gatewaypb.StoreGateway/Series err="rpc error: code = Aborted desc = fetch series for block 01F0FV9BE7HKM51VNBDDB0NA2C: expanded matching posting: get postings: invalid size" msg="gRPC\n"
level=error ts=2021-03-11T18:56:47.209284383Z caller=retry.go:73 org_id=fake traceID=5bbdb5d204eb6960 msg="error processing request" try=0 err="rpc error: code = Code(500) desc = {\"status\":\"error\",\"errorType\":\"internal\",\"error\":\"expanding series: failed to receive series from 10.0.26.97:9095: rpc error: code = Aborted desc = fetch series for block 01F0FV9BE7HKM51VNBDDB0NA2C: expanded matching posting: get postings: invalid size\"}"
panic: runtime error: slice bounds out of range [128:116]
goroutine 16726177 [running]:
github.com/thanos-io/thanos/pkg/store.(*bucketIndexReader).loadSeries(0xc00c6a2540, 0x2c2f8e0, 0xc012428780, 0xc0043e40e0, 0x3, 0x4, 0xc008769501, 0x1d4da0, 0x1d4e14, 0x0, ...)
/__w/cortex/cortex/vendor/github.com/thanos-io/thanos/pkg/store/bucket.go:2000 +0x9d9
github.com/thanos-io/thanos/pkg/store.(*bucketIndexReader).loadSeries(0xc00c6a2540, 0x2c2f8e0, 0xc012428780, 0xc0043e40e0, 0x3, 0x4, 0x0, 0x1d4da0, 0x1e4e20, 0x17cbe74, ...)
/__w/cortex/cortex/vendor/github.com/thanos-io/thanos/pkg/store/bucket.go:2016 +0x750
github.com/thanos-io/thanos/pkg/store.(*bucketIndexReader).PreloadSeries.func2(0xc0294ebc80, 0xc021b727e0)
/__w/cortex/cortex/vendor/github.com/thanos-io/thanos/pkg/store/bucket.go:1978 +0x9d
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc011c6da70, 0xc013467140)
/__w/cortex/cortex/vendor/golang.org/x/sync/errgroup/errgroup.go:57 +0x59
created by golang.org/x/sync/errgroup.(*Group).Go
/__w/cortex/cortex/vendor/golang.org/x/sync/errgroup/errgroup.go:54 +0x66
```

**Comment by pracucci** [comment]
Does it happen with Cortex 1.8.0 too?
