### ISSUE TITLE
Can't run any analyzer

### ISSUE THREAD

**Issue by AbderrahimBouhdida** [cortexproject/cortex#3983]
**Describe the bug**
Running any analyzer in cortex gives the following error : 
```
Traceback (most recent call last):
  File "Cyberprotect/CyberprotectAnalyzer.py", line 46, in <module>
    CyberprotectAnalyzer().run()
  File "Cyberprotect/CyberprotectAnalyzer.py", line 12, in __init__
    Analyzer.__init__(self)
  File "/usr/local/lib/python3.8/site-packages/cortexutils/analyzer.py", line 17, in __init__
    Worker.__init__(self, job_directory)
  File "/usr/local/lib/python3.8/site-packages/cortexutils/worker.py", line 31, in __init__
    self._input = json.load(sys.stdin)
  File "/usr/local/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**To Reproduce**
1. Start Cortex version 3.1.1-1 
![image](https://user-images.githubusercontent.com/10521433/111877718-d3716d00-89a4-11eb-977c-5140772f37bb.png)

2. Add any analyzer 
3. run analyzer 

![image](https://user-images.githubusercontent.com/10521433/111877764-0ddb0a00-89a5-11eb-95de-db05145df272.png)

**Expected behavior**
Analyzer return a report for the observables 

**Environment:**
 -Docker version 20.10.5, build 55c4c88
- ubuntu server 20.04

**Additional Context**
docker-compose.yml

```
version: "2"
services:
  elasticsearch:
    image: elasticsearch:7.8.1
    environment:
      - http.host=0.0.0.0
      - discovery.type=single-node
      - script.allowed_types=inline
      - thread_pool.search.queue_size=100000
      - thread_pool.write.queue_size=10000
  cortex:
    image: thehiveproject/cortex:latest
    environment:
      - job_directory=./cortex-jobs
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      #- ./tmp:/tmp
#- ${job_directory}:${job_directory}
    depends_on:
      - elasticsearch
    ports:
      - "0.0.0.0:9001:9001"
```

**Comment by pstibrany** [comment]
Hello, I think you want to send this issue to https://github.com/TheHive-Project/Cortex repository instead.

**Comment by AbderrahimBouhdida** [comment]
okay thank you !
