### ISSUE TITLE
query-frontend return: integer divide by zero

### ISSUE THREAD

**Issue by mrmassis** [cortexproject/cortex#4313]
Hi,
Im using the query-frontend but when make a querier in grafana I receive a error
```
2021/06/24 00:46:32 http: panic serving 10.46.16.105:33638: runtime error: integer divide by zero
goroutine 670 [running]:
net/http.(*conn).serve.func1(0xc000cf2140)
	/usr/local/go/src/net/http/server.go:1824 +0x153
panic(0x22ca800, 0x3bad160)
	/usr/local/go/src/runtime/panic.go:971 +0x499
github.com/opentracing-contrib/go-stdlib/nethttp.MiddlewareFunc.func5.1(0xc000c86c18, 0x2b8c8e0, 0xc000708360)
	/__w/cortex/cortex/vendor/github.com/opentracing-contrib/go-stdlib/nethttp/server.go:150 +0x1ab
panic(0x22ca800, 0x3bad160)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/cortexproject/cortex/pkg/querier/queryrange.nextIntervalBoundary(...)
	/__w/cortex/cortex/pkg/querier/queryrange/split_by_interval.go:79
github.com/cortexproject/cortex/pkg/querier/queryrange.splitQuery(0x2b89458, 0xc000bfbd60, 0x18, 0xc00107df50, 0x21c2ec0, 0x281e998)
	/__w/cortex/cortex/pkg/querier/queryrange/split_by_interval.go:66 +0x3d2
github.com/cortexproject/cortex/pkg/querier/queryrange.splitByInterval.Do(0x2b1c0a0, 0xc000888000, 0x2b61358, 0xc000792270, 0x7f822a2198f8, 0x3c12300, 0xc0002476d0, 0x2b78910, 0xc000e017a0, 0x2b607c0, ...)
	/__w/cortex/cortex/pkg/querier/queryrange/split_by_interval.go:43 +0x73
github.com/cortexproject/cortex/pkg/querier/queryrange.InstrumentMiddleware.func1.1.1(0x2b607c0, 0xc000c72840, 0x11, 0xc02d135a1d2e42eb)
	/__w/cortex/cortex/pkg/querier/queryrange/instrumentation.go:28 +0x62
github.com/weaveworks/common/instrument.CollectedRequest(0x2b607c0, 0xc000c72810, 0x26af89a, 0x11, 0x2b50560, 0xc0002a86c0, 0x2821ef8, 0xc0008a2928, 0x38, 0x48)
	/__w/cortex/cortex/vendor/github.com/weaveworks/common/instrument/instrument.go:152 +0x271
github.com/cortexproject/cortex/pkg/querier/queryrange.InstrumentMiddleware.func1.1(0x2b607c0, 0xc000c72810, 0x2b89458, 0xc000bfbd60, 0x252f4a0, 0xc000bfbd60, 0x661e9d, 0xc00067b3c0)
	/__w/cortex/cortex/pkg/querier/queryrange/instrumentation.go:26 +0xe9
github.com/cortexproject/cortex/pkg/querier/queryrange.HandlerFunc.Do(0xc000888040, 0x2b607c0, 0xc000c72810, 0x2b89458, 0xc000bfbd60, 0x21c2ec0, 0x281e998, 0x0, 0x404230)
	/__w/cortex/cortex/pkg/querier/queryrange/roundtrip.go:90 +0x4e
github.com/cortexproject/cortex/pkg/querier/queryrange.stepAlign.Do(0x2b1c0a0, 0xc000888040, 0x2b607c0, 0xc000c72810, 0x2b89458, 0xc000bfbb80, 0x1, 0x7f822a33f590, 0x8, 0x0)
	/__w/cortex/cortex/pkg/querier/queryrange/step_align.go:22 +0x1ad
github.com/cortexproject/cortex/pkg/querier/queryrange.InstrumentMiddleware.func1.1.1(0x2b607c0, 0xc000c72810, 0xa, 0xc02d135a1d2e320e)
	/__w/cortex/cortex/pkg/querier/queryrange/instrumentation.go:28 +0x62
github.com/weaveworks/common/instrument.CollectedRequest(0x2b607c0, 0xc000c727e0, 0x269fd20, 0xa, 0x2b50560, 0xc0002a86b8, 0x2821ef8, 0xc0008a2ca0, 0x21c4fc0, 0xc0003a8000)
	/__w/cortex/cortex/vendor/github.com/weaveworks/common/instrument/instrument.go:152 +0x271
github.com/cortexproject/cortex/pkg/querier/queryrange.InstrumentMiddleware.func1.1(0x2b607c0, 0xc000c727e0, 0x2b89458, 0xc000bfbb80, 0xc000507e6a, 0x0, 0xc000bff1f0, 0xc000507fc8)
	/__w/cortex/cortex/pkg/querier/queryrange/instrumentation.go:26 +0xe9
github.com/cortexproject/cortex/pkg/querier/queryrange.HandlerFunc.Do(0xc000888080, 0x2b607c0, 0xc000c727e0, 0x2b89458, 0xc000bfbb80, 0x1, 0x0, 0x0, 0x0)
	/__w/cortex/cortex/pkg/querier/queryrange/roundtrip.go:90 +0x4e
github.com/cortexproject/cortex/pkg/querier/queryrange.limitsMiddleware.Do(0x2b61358, 0xc000792270, 0x2b1c0a0, 0xc000888080, 0x2b607c0, 0xc000c725d0, 0x2b89458, 0xc000bfbb80, 0x0, 0x0, ...)
	/__w/cortex/cortex/pkg/querier/queryrange/limits.go:96 +0x2d7
github.com/cortexproject/cortex/pkg/querier/queryrange.roundTripper.RoundTrip(0x2b14c40, 0xc000247fc0, 0x2b1c120, 0xc0000d56e0, 0x2b67038, 0x3c12300, 0xc00005de00, 0xc00080e840, 0x2b78910, 0xc00080e840)
	/__w/cortex/cortex/pkg/querier/queryrange/roundtrip.go:269 +0x144
github.com/cortexproject/cortex/pkg/querier/queryrange.NewTripperware.func4.1(0xc00005de00, 0x60d3d5e8, 0xc01d2c529a, 0x4ab5da241a750)
	/__w/cortex/cortex/pkg/querier/queryrange/roundtrip.go:234 +0x24c
github.com/cortexproject/cortex/pkg/querier/queryrange.RoundTripFunc.RoundTrip(0xc0008880c0, 0xc00005de00, 0x3be1460, 0xc000bff100, 0xc00067b4c0)
	/__w/cortex/cortex/pkg/querier/queryrange/roundtrip.go:130 +0x30
github.com/cortexproject/cortex/pkg/frontend/transport.(*Handler).ServeHTTP(0xc000b299f0, 0x2b4b190, 0xc0004d9650, 0xc00005de00)
	/__w/cortex/cortex/pkg/frontend/transport/handler.go:114 +0x432
github.com/weaveworks/common/middleware.glob..func1.1(0x2b4b190, 0xc0004d9650, 0xc00005dd00)
	/__w/cortex/cortex/vendor/github.com/weaveworks/common/middleware/http_auth.go:17 +0x147
net/http.HandlerFunc.ServeHTTP(0xc000792768, 0x2b4b190, 0xc0004d9650, 0xc00005dd00)
	/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/NYTimes/gziphandler.GzipHandlerWithOpts.func1.1(0x2b54a60, 0xc000bf4340, 0xc00005dd00)
	/__w/cortex/cortex/vendor/github.com/NYTimes/gziphandler/gzip.go:338 +0x299
net/http.HandlerFunc.ServeHTTP(0xc0008084e0, 0x2b54a60, 0xc000bf4340, 0xc00005dd00)
	/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000b3ccc0, 0x2b54a60, 0xc000bf4340, 0xc00005db00)
	/__w/cortex/cortex/vendor/github.com/gorilla/mux/mux.go:212 +0xd3
github.com/weaveworks/common/middleware.Instrument.Wrap.func1.2(0x2b54a60, 0xc000bf4340)
	/__w/cortex/cortex/vendor/github.com/weaveworks/common/middleware/instrument.go:68 +0x4c
github.com/felixge/httpsnoop.CaptureMetricsFn(0x2b50590, 0xc000b29f90, 0xc000b13790, 0x2, 0x2b87fa8, 0xc00067b480)
	/__w/cortex/cortex/vendor/github.com/felixge/httpsnoop/capture_metrics.go:81 +0x24b
github.com/weaveworks/common/middleware.Instrument.Wrap.func1(0x2b50590, 0xc000b29f90, 0xc00005db00)
	/__w/cortex/cortex/vendor/github.com/weaveworks/common/middleware/instrument.go:67 +0x325
net/http.HandlerFunc.ServeHTTP(0xc000b294a0, 0x2b50590, 0xc000b29f90, 0xc00005db00)
	/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/weaveworks/common/middleware.Log.Wrap.func1(0x2b54b80, 0xc000b29f40, 0xc00005db00)
	/__w/cortex/cortex/vendor/github.com/weaveworks/common/middleware/logging.go:52 +0x1a9
net/http.HandlerFunc.ServeHTTP(0xc00076a340, 0x2b54b80, 0xc000b29f40, 0xc00005db00)
	/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/opentracing-contrib/go-stdlib/nethttp.MiddlewareFunc.func5(0x2b52c90, 0xc0008827e0, 0xc00005da00)
	/__w/cortex/cortex/vendor/github.com/opentracing-contrib/go-stdlib/nethttp/server.go:154 +0x5e4
net/http.HandlerFunc.ServeHTTP(0xc00076a380, 0x2b52c90, 0xc0008827e0, 0xc00005da00)
	/usr/local/go/src/net/http/server.go:2069 +0x44
net/http.serverHandler.ServeHTTP(0xc0008820e0, 0x2b52c90, 0xc0008827e0, 0xc00005da00)
	/usr/local/go/src/net/http/server.go:2887 +0xa3
net/http.(*conn).serve(0xc000cf2140, 0x2b607c0, 0xc00067b340)
	/usr/local/go/src/net/http/server.go:1952 +0x8cd
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3013 +0x39b
```

 - Infrastructure: Kubernetes
 -  Deployment tool: helm

**Storage Engine**
- [X] Blocks
- [ ] Chunks

**Additional Context**
The query suffle sharding is disable. 
The cortex is v1.9

**Comment by mrmassis** [comment]
max_queriers_per_tenant: 0

**Comment by pracucci** [comment]
What's the configured `split_queries_by_interval` (YAML config) or `-querier.split-queries-by-interval` (CLI flag)? I've the feeling it may have been set to a very low value.
