### ISSUE TITLE
Flaky test: testChunkFetcherStop failed (timed out) in CI

### ISSUE THREAD

**Issue by bboreham** [cortexproject/cortex#4456]
At https://github.com/cortexproject/cortex/runs/3496606494

```
panic: test timed out after 30m0s

goroutine 788 [running]:
testing.(*M).startAlarm.func1()
	/usr/local/go/src/testing/testing.go:1700 +0x11f
created by time.goFunc
	/usr/local/go/src/time/sleep.go:180 +0x52

goroutine 1 [chan receive, 29 minutes]:
testing.(*T).Run(0xc000342c00, 0x15d6b23, 0x10, 0x160ae68, 0x1)
	/usr/local/go/src/testing/testing.go:1239 +0x610
testing.runTests.func1(0xc000342c00)
	/usr/local/go/src/testing/testing.go:1511 +0xa7
testing.tRunner(0xc000342c00, 0xc0003dfce0)
	/usr/local/go/src/testing/testing.go:1193 +0x203
testing.runTests(0xc000340978, 0x1e09c20, 0x12, 0x12, 0xc04456c8e320c5ca, 0x1a319d80b8f, 0x1e18b00, 0xc0000b2148)
	/usr/local/go/src/testing/testing.go:1509 +0x613
testing.(*M).Run(0xc000167480, 0x0)
	/usr/local/go/src/testing/testing.go:1417 +0x3b4
main.main()
	_testmain.go:79 +0x237

goroutine 665 [select, 29 minutes]:
github.com/cortexproject/cortex/pkg/chunk/cache.NewMemcached.func1(0xc000490680)
	/__w/cortex/cortex/pkg/chunk/cache/memcached.go:94 +0x1cd
created by github.com/cortexproject/cortex/pkg/chunk/cache.NewMemcached
	/__w/cortex/cortex/pkg/chunk/cache/memcached.go:91 +0x585

goroutine 773 [chan send, 29 minutes]:
github.com/cortexproject/cortex/pkg/chunk.(*Fetcher).worker(0xc00030a780)
	/__w/cortex/cortex/pkg/chunk/chunk_store_utils.go:144 +0x2c5
created by github.com/cortexproject/cortex/pkg/chunk.NewChunkFetcher
	/__w/cortex/cortex/pkg/chunk/chunk_store_utils.go:114 +0x1e5

goroutine 666 [select, 29 minutes]:
github.com/cortexproject/cortex/pkg/chunk/cache.NewMemcached.func1(0xc000490680)
	/__w/cortex/cortex/pkg/chunk/cache/memcached.go:94 +0x1cd
created by github.com/cortexproject/cortex/pkg/chunk/cache.NewMemcached
	/__w/cortex/cortex/pkg/chunk/cache/memcached.go:91 +0x585

goroutine 201 [IO wait, 29 minutes]:
internal/poll.runtime_pollWait(0x7fefc2ca0b18, 0x72, 0x72)
	/usr/local/go/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc000214698, 0x72, 0x0, 0x0, 0x15ce30a)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0xe6
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc000214680, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:401 +0x32f
net.(*netFD).accept(0xc000214680, 0x0, 0x0, 0xc0002107a8)
	/usr/local/go/src/net/fd_unix.go:172 +0x58
net.(*TCPListener).accept(0xc00000e948, 0xc000066e98, 0x10b84ea, 0xc000000018)
	/usr/local/go/src/net/tcpsock_posix.go:139 +0x50
net.(*TCPListener).Accept(0xc00000e948, 0x17835d0, 0xc0000b09d8, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock.go:261 +0x8e
github.com/alicebob/miniredis/v2/server.(*Server).serve(0xc000210780, 0x17768b0, 0xc00000e948)
	/__w/cortex/cortex/vendor/github.com/alicebob/miniredis/v2/server/server.go:92 +0x4f
github.com/alicebob/miniredis/v2/server.newServer.func1(0xc000210780, 0x17768b0, 0xc00000e948)
	/__w/cortex/cortex/vendor/github.com/alicebob/miniredis/v2/server/server.go:72 +0xb3
created by github.com/alicebob/miniredis/v2/server.newServer
	/__w/cortex/cortex/vendor/github.com/alicebob/miniredis/v2/server/server.go:70 +0x14e

goroutine 200 [IO wait, 29 minutes]:
internal/poll.runtime_pollWait(0x7fefc2ca0c00, 0x72, 0x72)
	/usr/local/go/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc000214598, 0x72, 0x0, 0x0, 0x15ce30a)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0xe6
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc000214580, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:401 +0x32f
net.(*netFD).accept(0xc000214580, 0x0, 0x0, 0xc000210758)
	/usr/local/go/src/net/fd_unix.go:172 +0x58
net.(*TCPListener).accept(0xc00000e7f8, 0xc000250e98, 0x10b84ea, 0xc000000018)
	/usr/local/go/src/net/tcpsock_posix.go:139 +0x50
net.(*TCPListener).Accept(0xc00000e7f8, 0x17835d0, 0xc0000b09f0, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock.go:261 +0x8e
github.com/alicebob/miniredis/v2/server.(*Server).serve(0xc000210730, 0x17768b0, 0xc00000e7f8)
	/__w/cortex/cortex/vendor/github.com/alicebob/miniredis/v2/server/server.go:92 +0x4f
github.com/alicebob/miniredis/v2/server.newServer.func1(0xc000210730, 0x17768b0, 0xc00000e7f8)
	/__w/cortex/cortex/vendor/github.com/alicebob/miniredis/v2/server/server.go:72 +0xb3
created by github.com/alicebob/miniredis/v2/server.newServer
	/__w/cortex/cortex/vendor/github.com/alicebob/miniredis/v2/server/server.go:70 +0x14e

goroutine 699 [chan receive, 29 minutes]:
testing.(*T).Run(0xc000378000, 0x15d2438, 0xb, 0xc0007590b0, 0x1)
	/usr/local/go/src/testing/testing.go:1239 +0x610
github.com/cortexproject/cortex/pkg/chunk/cache_test.testCache(0xc000378000, 0x1776b20, 0xc00028c000)
	/__w/cortex/cortex/pkg/chunk/cache/cache_test.go:177 +0x63a
github.com/cortexproject/cortex/pkg/chunk/cache_test.TestTieredSimple(0xc000378000)
	/__w/cortex/cortex/pkg/chunk/cache/tiered_test.go:19 +0x2a5
testing.tRunner(0xc000378000, 0x160ae68)
	/usr/local/go/src/testing/testing.go:1193 +0x203
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1238 +0x5d8

goroutine 189 [IO wait, 29 minutes]:
internal/poll.runtime_pollWait(0x7fefc2ca0eb8, 0x72, 0x72)
	/usr/local/go/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc000214098, 0x72, 0x0, 0x0, 0x15ce30a)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0xe6
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc000214080, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:401 +0x32f
net.(*netFD).accept(0xc000214080, 0x0, 0x0, 0xc000210078)
	/usr/local/go/src/net/fd_unix.go:172 +0x58
net.(*TCPListener).accept(0xc00000e318, 0xc000065e98, 0x10b84ea, 0xc000000018)
	/usr/local/go/src/net/tcpsock_posix.go:139 +0x50
net.(*TCPListener).Accept(0xc00000e318, 0x17835d0, 0xc000010078, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock.go:261 +0x8e
github.com/alicebob/miniredis/v2/server.(*Server).serve(0xc000210050, 0x17768b0, 0xc00000e318)
	/__w/cortex/cortex/vendor/github.com/alicebob/miniredis/v2/server/server.go:92 +0x4f
github.com/alicebob/miniredis/v2/server.newServer.func1(0xc000210050, 0x17768b0, 0xc00000e318)
	/__w/cortex/cortex/vendor/github.com/alicebob/miniredis/v2/server/server.go:72 +0xb3
created by github.com/alicebob/miniredis/v2/server.newServer
	/__w/cortex/cortex/vendor/github.com/alicebob/miniredis/v2/server/server.go:70 +0x14e

goroutine 198 [IO wait, 29 minutes]:
internal/poll.runtime_pollWait(0x7fefc2ca0dd0, 0x72, 0x72)
	/usr/local/go/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc000214498, 0x72, 0x0, 0x0, 0x15ce30a)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0xe6
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc000214480, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:401 +0x32f
net.(*netFD).accept(0xc000214480, 0x0, 0x0, 0xc000210708)
	/usr/local/go/src/net/fd_unix.go:172 +0x58
net.(*TCPListener).accept(0xc00000e6a8, 0xc000067e98, 0x10b84ea, 0xc000000018)
	/usr/local/go/src/net/tcpsock_posix.go:139 +0x50
net.(*TCPListener).Accept(0xc00000e6a8, 0x17835d0, 0xc000010090, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock.go:261 +0x8e
github.com/alicebob/miniredis/v2/server.(*Server).serve(0xc0002106e0, 0x17768b0, 0xc00000e6a8)
	/__w/cortex/cortex/vendor/github.com/alicebob/miniredis/v2/server/server.go:92 +0x4f
github.com/alicebob/miniredis/v2/server.newServer.func1(0xc0002106e0, 0x17768b0, 0xc00000e6a8)
	/__w/cortex/cortex/vendor/github.com/alicebob/miniredis/v2/server/server.go:72 +0xb3
created by github.com/alicebob/miniredis/v2/server.newServer
	/__w/cortex/cortex/vendor/github.com/alicebob/miniredis/v2/server/server.go:70 +0x14e

goroutine 664 [select, 29 minutes]:
github.com/cortexproject/cortex/pkg/chunk/cache.NewMemcached.func1(0xc000490680)
	/__w/cortex/cortex/pkg/chunk/cache/memcached.go:94 +0x1cd
created by github.com/cortexproject/cortex/pkg/chunk/cache.NewMemcached
	/__w/cortex/cortex/pkg/chunk/cache/memcached.go:91 +0x585

goroutine 725 [semacquire, 29 minutes]:
sync.runtime_Semacquire(0xc00030a7a4)
	/usr/local/go/src/runtime/sema.go:56 +0x45
sync.(*WaitGroup).Wait(0xc00030a7a4)
	/usr/local/go/src/sync/waitgroup.go:130 +0xe5
github.com/cortexproject/cortex/pkg/chunk.(*Fetcher).Stop(0xc00030a780)
	/__w/cortex/cortex/pkg/chunk/chunk_store_utils.go:128 +0x7e
github.com/cortexproject/cortex/pkg/chunk/cache_test.testChunkFetcherStop(0xc0003e8d80, 0x1776b20, 0xc00028c000, 0xc0000ba800, 0x6f, 0x80, 0xc000012000, 0x6f, 0x88)
	/__w/cortex/cortex/pkg/chunk/cache/cache_test.go:143 +0x253
github.com/cortexproject/cortex/pkg/chunk/cache_test.testCache.func5(0xc0003e8d80)
	/__w/cortex/cortex/pkg/chunk/cache/cache_test.go:180 +0x206
testing.tRunner(0xc0003e8d80, 0xc0007590b0)
	/usr/local/go/src/testing/testing.go:1193 +0x203
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1238 +0x5d8

goroutine 673 [select, 29 minutes]:
github.com/cortexproject/cortex/pkg/chunk/cache.NewMemcached.func1(0xc000490080)
	/__w/cortex/cortex/pkg/chunk/cache/memcached.go:94 +0x1cd
created by github.com/cortexproject/cortex/pkg/chunk/cache.NewMemcached
	/__w/cortex/cortex/pkg/chunk/cache/memcached.go:91 +0x585

goroutine 771 [chan send, 29 minutes]:
github.com/cortexproject/cortex/pkg/chunk.(*Fetcher).worker(0xc00030a780)
	/__w/cortex/cortex/pkg/chunk/chunk_store_utils.go:144 +0x2c5
created by github.com/cortexproject/cortex/pkg/chunk.NewChunkFetcher
	/__w/cortex/cortex/pkg/chunk/chunk_store_utils.go:114 +0x1e5

goroutine 662 [select, 29 minutes]:
github.com/cortexproject/cortex/pkg/chunk/cache.NewMemcached.func1(0xc000490680)
	/__w/cortex/cortex/pkg/chunk/cache/memcached.go:94 +0x1cd
created by github.com/cortexproject/cortex/pkg/chunk/cache.NewMemcached
	/__w/cortex/cortex/pkg/chunk/cache/memcached.go:91 +0x585

goroutine 663 [select, 29 minutes]:
github.com/cortexproject/cortex/pkg/chunk/cache.NewMemcached.func1(0xc000490680)
	/__w/cortex/cortex/pkg/chunk/cache/memcached.go:94 +0x1cd
created by github.com/cortexproject/cortex/pkg/chunk/cache.NewMemcached
	/__w/cortex/cortex/pkg/chunk/cache/memcached.go:91 +0x585

goroutine 670 [select, 29 minutes]:
github.com/cortexproject/cortex/pkg/chunk/cache.NewMemcached.func1(0xc000490080)
	/__w/cortex/cortex/pkg/chunk/cache/memcached.go:94 +0x1cd
created by github.com/cortexproject/cortex/pkg/chunk/cache.NewMemcached
	/__w/cortex/cortex/pkg/chunk/cache/memcached.go:91 +0x585

goroutine 672 [select, 29 minutes]:
github.com/cortexproject/cortex/pkg/chunk/cache.NewMemcached.func1(0xc000490080)
	/__w/cortex/cortex/pkg/chunk/cache/memcached.go:94 +0x1cd
created by github.com/cortexproject/cortex/pkg/chunk/cache.NewMemcached
	/__w/cortex/cortex/pkg/chunk/cache/memcached.go:91 +0x585

goroutine 669 [select, 29 minutes]:
github.com/cortexproject/cortex/pkg/chunk/cache.NewMemcached.func1(0xc000490080)
	/__w/cortex/cortex/pkg/chunk/cache/memcached.go:94 +0x1cd
created by github.com/cortexproject/cortex/pkg/chunk/cache.NewMemcached
	/__w/cortex/cortex/pkg/chunk/cache/memcached.go:91 +0x585

goroutine 671 [select, 29 minutes]:
github.com/cortexproject/cortex/pkg/chunk/cache.NewMemcached.func1(0xc000490080)
	/__w/cortex/cortex/pkg/chunk/cache/memcached.go:94 +0x1cd
created by github.com/cortexproject/cortex/pkg/chunk/cache.NewMemcached
	/__w/cortex/cortex/pkg/chunk/cache/memcached.go:91 +0x585
FAIL	github.com/cortexproject/cortex/pkg/chunk/cache	1800.044s
```

**Comment by bboreham** [comment]
Also at https://github.com/cortexproject/cortex/runs/4190713918 - different test but same hang.
