### ISSUE TITLE
Ingester slice bounds out of range panic

### ISSUE THREAD

**Issue by yeya24** [cortexproject/cortex#4974]
**Describe the bug**

I don't have enough time to dive deep into this right now, but I suspect it is related to the YOLO buf.
It is reproducible for me locally by starting the ingester while having a prometheus server remote writing to it.

```
level=info ts=2022-11-18T06:52:45.336621Z caller=lifecycler.go:638 msg="existing entry found in ring" state=ACTIVE tokens=512 ring=ingester
panic: runtime error: slice bounds out of range [::33] with capacity 0

goroutine 137 [running]:
github.com/cespare/xxhash.writeBlocks(0x1400005e320, {0x14001344b20, 0x21, 0x0})
        /Users/benye/hub/gowork/cortex/vendor/github.com/cespare/xxhash/xxhash_other.go:67 +0x338
github.com/cespare/xxhash.(*xxh).Write(0x1400005e320, {0x14001344b20, 0x21, 0x0})
        /Users/benye/hub/gowork/cortex/vendor/github.com/cespare/xxhash/xxhash.go:86 +0x494
github.com/cortexproject/cortex/pkg/ingester.fingerprint({0x1400136e500, 0x8, 0x14})
        /Users/benye/hub/gowork/cortex/pkg/ingester/active_series.go:75 +0x2bc
github.com/cortexproject/cortex/pkg/ingester.(*ActiveSeries).UpdateSeries(0x14000272000, {0x1400136e500, 0x8, 0x14}, {0xc0d5e8dba15631e8, 0xb7a655045, 0x106148380}, 0x140009f4188)
        /Users/benye/hub/gowork/cortex/pkg/ingester/active_series.go:57 +0x4c
github.com/cortexproject/cortex/pkg/ingester.(*Ingester).Push(0x14000635500, {0x105290430, 0x14001538210}, 0x14000c72e80)
        /Users/benye/hub/gowork/cortex/pkg/ingester/ingester.go:1036 +0x1518
github.com/cortexproject/cortex/pkg/ingester/client._Ingester_Push_Handler.func1({0x105290430, 0x14001538210}, {0x1051c82c0, 0x14000c72e80})
        /Users/benye/hub/gowork/cortex/pkg/ingester/client/ingester.pb.go:3037 +0xb0
github.com/cortexproject/cortex/pkg/cortex.ThanosTracerUnaryInterceptor({0x105290430, 0x140015381e0}, {0x1051c82c0, 0x14000c72e80}, 0x105290430, 0x1400000f8a8)
        /Users/benye/hub/gowork/cortex/pkg/cortex/tracing.go:14 +0xa4
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1({0x105290430, 0x140015381e0}, {0x1051c82c0, 0x14000c72e80})
        /Users/benye/hub/gowork/cortex/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:25 +0x78
github.com/cortexproject/cortex/pkg/util/fakeauth.glob..func2({0x105290430, 0x140015381e0}, {0x1051c82c0, 0x14000c72e80}, 0x140008588c0, 0x140008588e0)
        /Users/benye/hub/gowork/cortex/pkg/util/fakeauth/fake_auth.go:60 +0x80
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1({0x105290430, 0x140015381b0}, {0x1051c82c0, 0x14000c72e80})
        /Users/benye/hub/gowork/cortex/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:25 +0x78
github.com/weaveworks/common/middleware.UnaryServerInstrumentInterceptor.func1({0x105290430, 0x140015381b0}, {0x1051c82c0, 0x14000c72e80}, 0x140008588c0, 0x14000858900)
        /Users/benye/hub/gowork/cortex/vendor/github.com/weaveworks/common/middleware/grpc_instrumentation.go:35 +0x88
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1({0x105290430, 0x140015381b0}, {0x1051c82c0, 0x14000c72e80})
        /Users/benye/hub/gowork/cortex/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:25 +0x78
github.com/opentracing-contrib/go-grpc.OpenTracingServerInterceptor.func1({0x105290430, 0x140015381b0}, {0x1051c82c0, 0x14000c72e80}, 0x140008588c0, 0x14000858920)
        /Users/benye/hub/gowork/cortex/vendor/github.com/opentracing-contrib/go-grpc/server.go:57 +0x500
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1({0x105290430, 0x14000663fb0}, {0x1051c82c0, 0x14000c72e80})
        /Users/benye/hub/gowork/cortex/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:25 +0x78
github.com/weaveworks/common/middleware.GRPCServerLog.UnaryServerInterceptor({{0x1052a4cc0, 0x14000bacf10}, 0x0, 0x0}, {0x105290430, 0x14000663fb0}, {0x1051c82c0, 0x14000c72e80}, 0x140008588c0, 0x14000858940)
        /Users/benye/hub/gowork/cortex/vendor/github.com/weaveworks/common/middleware/grpc_logging.go:30 +0x94
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1({0x105290430, 0x14000663fb0}, {0x1051c82c0, 0x14000c72e80})
        /Users/benye/hub/gowork/cortex/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:25 +0x78
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1({0x105290430, 0x14000663fb0}, {0x1051c82c0, 0x14000c72e80}, 0x140008588c0, 0x1400000f8a8)
        /Users/benye/hub/gowork/cortex/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:34 +0x118
github.com/cortexproject/cortex/pkg/ingester/client._Ingester_Push_Handler({0x105247a60, 0x14000635500}, {0x105290430, 0x14000663fb0}, 0x14000141d40, 0x14000c37ec0)
        /Users/benye/hub/gowork/cortex/pkg/ingester/client/ingester.pb.go:3039 +0x1e8
google.golang.org/grpc.(*Server).processUnaryRPC(0x14000aa1500, {0x1052a3cb8, 0x140006be340}, 0x14000bfe360, 0x14000c369c0, 0x1061268e0, 0x0)
        /Users/benye/hub/gowork/cortex/vendor/google.golang.org/grpc/server.go:1282 +0x10f4
google.golang.org/grpc.(*Server).handleStream(0x14000aa1500, {0x1052a3cb8, 0x140006be340}, 0x14000bfe360, 0x0)
        /Users/benye/hub/gowork/cortex/vendor/google.golang.org/grpc/server.go:1619 +0x714
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        /Users/benye/hub/gowork/cortex/vendor/google.golang.org/grpc/server.go:921 +0xc4
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /Users/benye/hub/gowork/cortex/vendor/google.golang.org/grpc/server.go:919 +0x390
Exiting.
```

**To Reproduce**
1. Start Cortex (SHA or version)
2. Perform Operations(Read/Write/Others)

**Expected behavior**

**Environment:**
 - Infrastructure: [e.g., Kubernetes, bare-metal, laptop]
 - Deployment tool: [e.g., helm, jsonnet]

**Additional Context**

**Comment by yeya24** [comment]
Seems the panic came from `xxhash_other.go:67` probably it is related to my M1 MBP only.
