### ISSUE TITLE
Hang in `Distributor.Push()`

### ISSUE THREAD

**Issue by bboreham** [cortexproject/cortex#551]
We had a `ruler` process hang; `Push()` is waiting in two goroutines for something to come back to it; however there are no stack traces showing any of the `sendSamples` routines it is waiting on.  Many other things in the environment were hosed: Consul had no leader, etc.

I can't see by eyeballing `sendSamples` how it can go wrong, however the stack traces say it did.

```
goroutine 26113781 [select, 364 minutes]:
github.com/weaveworks/cortex/pkg/distributor.(*Distributor).Push(0xc42059e500, 0x7f517c5f39c0, 0xc42f6c34a0, 0xc43bf56720, 0x3083918, 0x0, 0x0)
	/go/src/github.com/weaveworks/cortex/pkg/distributor/distributor.go:364 +0xec8
github.com/weaveworks/cortex/pkg/ruler.appenderAdapter.Append(0x2ff7060, 0xc42059e500, 0x7f517c5f39c0, 0xc42f6c34a0, 0xc4325366e0, 0x0, 0x0)
	/go/src/github.com/weaveworks/cortex/pkg/ruler/compat.go:28 +0xb2
github.com/weaveworks/cortex/pkg/ruler.(*appenderAdapter).Append(0xc433a475e0, 0xc4325366e0, 0x0, 0x0)
	<autogenerated>:2 +0x72
github.com/weaveworks/cortex/vendor/github.com/prometheus/prometheus/rules.(*Group).Eval.func1(0xc42a4ffe10, 0x1fd2b69, 0x9, 0xc42d8eb8b0, 0x15e2d655b20, 0x3012b60, 0xc420550990)
	/go/src/github.com/weaveworks/cortex/vendor/github.com/prometheus/prometheus/rules/manager.go:296 +0x247
created by github.com/weaveworks/cortex/vendor/github.com/prometheus/prometheus/rules.(*Group).Eval
	/go/src/github.com/weaveworks/cortex/vendor/github.com/prometheus/prometheus/rules/manager.go:315 +0x138

goroutine 26113740 [select, 364 minutes]:
github.com/weaveworks/cortex/pkg/distributor.(*Distributor).Push(0xc42059e500, 0x7f517c5f39c0, 0xc42f6c34a0, 0xc43bf56700, 0x3083918, 0x0, 0x0)
	/go/src/github.com/weaveworks/cortex/pkg/distributor/distributor.go:364 +0xec8
github.com/weaveworks/cortex/pkg/ruler.appenderAdapter.Append(0x2ff7060, 0xc42059e500, 0x7f517c5f39c0, 0xc42f6c34a0, 0xc43ff07580, 0x0, 0x0)
	/go/src/github.com/weaveworks/cortex/pkg/ruler/compat.go:28 +0xb2
github.com/weaveworks/cortex/pkg/ruler.(*appenderAdapter).Append(0xc433a475e0, 0xc43ff07580, 0x0, 0x0)
	<autogenerated>:2 +0x72
github.com/weaveworks/cortex/vendor/github.com/prometheus/prometheus/rules.(*Group).Eval.func1(0xc42a4ffe10, 0x1fd2b69, 0x9, 0xc42d8eb8b0, 0x15e2d655b20, 0x3012b60, 0xc420b933b0)
	/go/src/github.com/weaveworks/cortex/vendor/github.com/prometheus/prometheus/rules/manager.go:296 +0x247
created by github.com/weaveworks/cortex/vendor/github.com/prometheus/prometheus/rules.(*Group).Eval
	/go/src/github.com/weaveworks/cortex/vendor/github.com/prometheus/prometheus/rules/manager.go:315 +0x138
```

**Comment by tomwilkie** [comment]
Was this pre or post the grpc heathchecking?  I seem to recall that fixed a lot of these problems.  Perhaps this can be closed?
