### ISSUE TITLE
Ruler panics with nil pointer exception when started without flags

### ISSUE THREAD

**Issue by juliusv** [cortexproject/cortex#751]
```
./cmd/ruler/ruler 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0xc7fcc5]

goroutine 1 [running]:
github.com/weaveworks/cortex/pkg/chunk/storage.NewStorageClient(0x20ffb62, 0x3, 0x0, 0x4000000000000000, 0x0, 0xa, 0x20, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/weaveworks/cortex/pkg/chunk/storage/factory.go:39 +0x75
main.main()
	/go/src/github.com/weaveworks/cortex/cmd/ruler/main.go:51 +0x48c
```

It should of course give a helpful error message about something missing instead.

**Comment by gouthamve** [comment]
Not an issue anymore. Closing.
