### ISSUE TITLE
Test flake in config database code

### ISSUE THREAD

**Issue by bboreham** [cortexproject/cortex#863]
Passed on re-run.
https://circleci.com/gh/weaveworks/cortex/2329

```
MIGRATIONS_DIR=$(pwd)/cmd/configs/migrations make BUILD_IN_CONTAINER=false configs-integration-test
protoc -I ./vendor:./pkg/ingester/client --gogoslick_out=plugins=grpc:./pkg/ingester/client ./pkg/ingester/client/cortex.proto
protoc -I ./vendor:./pkg/ring --gogoslick_out=plugins=grpc:./pkg/ring ./pkg/ring/ring.proto
/bin/bash -c "go test -tags 'netgo integration' -timeout 30s ./pkg/configs/... ./pkg/ruler/..."
ok  	github.com/weaveworks/cortex/pkg/configs	0.006s
panic: test timed out after 30s

goroutine 37 [running]:
testing.(*M).startAlarm.func1()
	/usr/local/go/src/testing/testing.go:1240 +0xfc
created by time.goFunc
	/usr/local/go/src/time/sleep.go:172 +0x44

goroutine 1 [chan receive]:
testing.(*T).Run(0xc42023e0f0, 0x97233f, 0xc, 0x9932b0, 0x47b446)
	/usr/local/go/src/testing/testing.go:825 +0x301
testing.runTests.func1(0xc42023e000)
	/usr/local/go/src/testing/testing.go:1063 +0x64
testing.tRunner(0xc42023e000, 0xc4200addf8)
	/usr/local/go/src/testing/testing.go:777 +0xd0
testing.runTests(0xc420136cc0, 0xc53420, 0xd, 0xd, 0x411c59)
	/usr/local/go/src/testing/testing.go:1061 +0x2c4
testing.(*M).Run(0xc420150200, 0x0)
	/usr/local/go/src/testing/testing.go:978 +0x171
main.main()
	_testmain.go:68 +0x151

goroutine 7 [syscall]:
os/signal.signal_recv(0x434be8)
	/usr/local/go/src/runtime/sigqueue.go:139 +0xa6
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 10 [sleep]:
time.Sleep(0x3b9aca000)
	/usr/local/go/src/runtime/time.go:102 +0x166
github.com/weaveworks/cortex/pkg/configs/db/postgres.dbWait(0xc4200ed720, 0x8, 0x98c41a)
	/go/src/github.com/weaveworks/cortex/pkg/configs/db/postgres/postgres.go:59 +0xc0
github.com/weaveworks/cortex/pkg/configs/db/postgres.New(0x98c41a, 0x3a, 0xc42002c00f, 0x3b, 0x0, 0x0, 0x0, 0xc420240090, 0x4eaafd, 0xa9afd0)
	/go/src/github.com/weaveworks/cortex/pkg/configs/db/postgres/postgres.go:71 +0x92
github.com/weaveworks/cortex/pkg/configs/db/dbtest.Setup(0xc42023e0f0, 0xc4200b8d40, 0xf)
	/go/src/github.com/weaveworks/cortex/pkg/configs/db/dbtest/integration.go:27 +0xa7
github.com/weaveworks/cortex/pkg/configs/api_test.setup(0xc42023e0f0)
	/go/src/github.com/weaveworks/cortex/pkg/configs/api/helpers_test.go:29 +0x2f
github.com/weaveworks/cortex/pkg/configs/api_test.Test_Root_OK(0xc42023e0f0)
	/go/src/github.com/weaveworks/cortex/pkg/configs/api/api_test.go:34 +0x2f
testing.tRunner(0xc42023e0f0, 0x9932b0)
	/usr/local/go/src/testing/testing.go:777 +0xd0
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:824 +0x2e0

goroutine 13 [select]:
database/sql.(*DB).connectionOpener(0xc4200ed720, 0x9d6040, 0xc4200b8ec0)
	/usr/local/go/src/database/sql/sql.go:935 +0x119
created by database/sql.OpenDB
	/usr/local/go/src/database/sql/sql.go:634 +0x178

goroutine 14 [select]:
database/sql.(*DB).connectionResetter(0xc4200ed720, 0x9d6040, 0xc4200b8ec0)
	/usr/local/go/src/database/sql/sql.go:948 +0x12a
created by database/sql.OpenDB
	/usr/local/go/src/database/sql/sql.go:635 +0x1ae
FAIL	github.com/weaveworks/cortex/pkg/configs/api	30.009s
```

**Comment by gouthamve** [comment]
Doesn't flake anymore ;)
